// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6bxQ2Utm8mDIe9fq39bfNTt36u5acYzQ',
    appId: '1:858906526021:web:7af5b800dd867aa95bfe2c',
    messagingSenderId: '858906526021',
    projectId: 'ems-app-637cc',
    authDomain: 'ems-app-637cc.firebaseapp.com',
    storageBucket: 'ems-app-637cc.appspot.com',
    measurementId: 'G-03R460JVX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcBtcYb8KgeXWP9KhDHKnMe-5gm-dKWnI',
    appId: '1:858906526021:android:f4079169474bddff5bfe2c',
    messagingSenderId: '858906526021',
    projectId: 'ems-app-637cc',
    storageBucket: 'ems-app-637cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoAxzpWHBdl0RaPauRv26RmmQKX2yyhmo',
    appId: '1:858906526021:ios:6b4c9ffa66bfcd045bfe2c',
    messagingSenderId: '858906526021',
    projectId: 'ems-app-637cc',
    storageBucket: 'ems-app-637cc.appspot.com',
    iosClientId: '858906526021-8u619hqd69bv64d4vr6seleutvpopobh.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventmanagementapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoAxzpWHBdl0RaPauRv26RmmQKX2yyhmo',
    appId: '1:858906526021:ios:3f02aaa4b73b65ea5bfe2c',
    messagingSenderId: '858906526021',
    projectId: 'ems-app-637cc',
    storageBucket: 'ems-app-637cc.appspot.com',
    iosClientId: '858906526021-1ndm9qk3mpcsu9ankglpk0vreti9e30j.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventmanagementapp.RunnerTests',
  );
}
